---
driver:
  name: docker_cli
  platform: rhel
  image: centos:centos6
  run_command:
    # cf. https://github.com/neillturner/kitchen-ansible/blob/b83ea0ac8bc8075b08a8a5c954eb1cfefbbaabb9/lib/kitchen/provisioner/ansible_playbook.rb#L336-L341
    - rpm -ivh http://ftp.iij.ad.jp/pub/linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - yum makecache
    - yum -y install ansible libselinux-python git
    # cf. https://github.com/neillturner/kitchen-ansible/blob/b83ea0ac8bc8075b08a8a5c954eb1cfefbbaabb9/lib/kitchen/provisioner/ansible_playbook.rb#L120-L154
    - yum install -y centos-release-SCL
    - yum install -y ruby193 ruby193-ruby-devel
    - source /opt/rh/ruby193/enable
    - echo "/opt/rh/ruby193/root/usr/lib64" | tee -a /etc/ld.so.conf
    - ldconfig
    - ln -s /opt/rh/ruby193/root/usr/bin/ruby /usr/bin/ruby
    - ln -s /opt/rh/ruby193/root/usr/bin/gem /usr/bin/gem
    # prerequisites
    - yum install -y which unzip

transport:
  name: docker_cli

platforms:
  - name: centos6

provisioner:
  name: ansible_playbook
  playbook: default.yml
  ansible_verbose: true
  ansible_verbosity: 2

verifier:
  ruby_bindir: '/usr/bin'

suites:
  - &consul-server
    name: &cs01
      consul-server-01
    driver: &consul-driver
      hostname: *cs01
      container_name: consul_server_01
      publish:
        - 8400
        - 8500
        - 8600
        - 8600/udp
    provisioner:
      hosts: consul-server
      playbook: consul-server.yml
      extra_vars:
        consul_bootstrap_expect: 3
  - <<: *consul-server
    name: &cs02
      consul-server-02
    driver:
      <<: *consul-driver
      hostname: *cs02
      container_name: consul_server_02
      link: consul_server_01
  - <<: *consul-server
    name: &cs03
      consul-server-03
    driver:
      <<: *consul-driver
      hostname: *cs03
      container_name: consul_server_03
      link:
        - consul_server_01
        - consul_server_02
